openapi: 3.1.0
info:
  title: Billard API
  description: API für die Verwaltung von Billard-Spielen und Spielern
  version: 1.0.0
servers:
  - url: 'https://billard.bybrauns.com/api/v1'
    description: Billard API Produktionsserver
paths:
  '/home':
    get:
      summary: Home
      description: Zeigt aktuelle Spiele und deren Status an
      operationId: getHome
      tags:
        - Home
      responses:
        '200':
          description: Liste der aktuellen Spiele erfolgreich abgerufen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HomeResponse'
              example:
                - game:
                    id: '1'
                    status: IN_PROGRESS
                    date: '2023-10-01T12:00:00Z'
                    players:
                      - id: '1'
                        name: Player 1
                      - id: '2'
                        name: Player 2
                    actions:
                      - START
                      - ABORT
                      - PAUSE
                      - RESUME
                      - FINISH
  '/game':
    post:
      summary: Neues Spiel erstellen
      description: Erstellt ein neues Billard-Spiel mit den angegebenen Spielern
      operationId: createGame
      tags:
        - Game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                players:
                  type: array
                  items:
                    $ref: '#/components/schemas/PlayerInput'
      responses:
        '201':
          description: Spiel erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  '/game/{gameId}/{action}':
    post:
      summary: Game Action
      description: Führt eine Aktion für ein bestimmtes Spiel aus
      operationId: gameAction
      tags:
        - Game
      parameters:
        - name: gameId
          in: path
          required: true
          description: ID des Spiels
          schema:
            type: string
        - name: action
          in: path
          required: true
          description: Auszuführende Aktion
          schema:
            type: string
            enum:
              - START
              - ABORT
              - PAUSE
              - RESUME
              - FINISH
      responses:
        '200':
          description: Aktion erfolgreich ausgeführt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: Konflikt - Aktion kann im aktuellen Spielzustand nicht ausgeführt werden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/game/{gameId}':
    get:
      summary: Spiel abrufen
      description: Ruft die Details eines bestimmten Spiels ab
      operationId: getGame
      tags:
        - Game
      parameters:
        - name: gameId
          in: path
          required: true
          description: ID des Spiels
          schema:
            type: string
      responses:
        '200':
          description: Spieldetails erfolgreich abgerufen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
components:
  responses:
    NotFound:
      description: Ressource nicht gefunden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Serverfehler
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Fehlerbeschreibung
      required:
        - message

    PlayerInput:
      type: object
      properties:
        name:
          type: string
          description: Name des Spielers
      required:
        - name

    HomeResponse:
      type: array
      items:
        type: object
        properties:
          game:
            $ref: '#/components/schemas/Game'
        required:
          - game

    Player:
      type: object
      properties:
        name:
          type: string
          description: Name des Spielers
      required:
        - name

    GameStatus:
      type: string
      enum:
        - NOT_STARTED
        - IN_PROGRESS
        - PAUSED
        - FINISHED
        - ABORTED
      description: Aktueller Status des Spiels

    Game:
      type: object
      properties:
        id:
          type: string
          description: ID des Spiels
        createDate:
          type: string
          format: date-time
          description: Datum und Zeit der Spiel Erstellung
        startDate:
          type: string
          format: date-time
          description: Datum und Zeit des Spiels
          nullable: true
        endDate:
          type: string
          format: date-time
          description: Datum und Zeit des Spiels
          nullable: true
        duration:
          type: integer
          description: Dauer des Spiels in Minuten
          nullable: true
        status:
          $ref: '#/components/schemas/GameStatus'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
          description: Liste der teilnehmenden Spieler
        actions:
          $ref: '#/components/schemas/GameActions'
      required:
        - id
        - date
        - status
        - players
        - actions
    GameActions:
        type: array
        items:
            type: string
            enum:
            - START
            - ABORT
            - PAUSE
            - RESUME
            - FINISH
        description: Liste der möglichen Aktionen im aktuellen Spielzustand
